config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get '/admin_edit/:id' => 'users#admin_edit', as: :admin_edit
  resources :books_on_loans
  resources :books do

    get 'check_out', :on => :collection
    get 'check_in', :on => :collection
    get 'list_onloan', :on => :collection
    post 'list_onloan', :on => :collection
    post 'check_out', :on => :collection
    post 'check_in', :on => :collection

    collection do
      get :edit_multiple
      put :update_multiple
    end
  end
   resources :welcome do
     get 'book_search', :on => :collection
     post 'book_search', :on => :collection
   end
  resources :roles_users
  resources :roles
  resources :users do
    collection do
      get 'admin_edit'

      get 'autocomplete_role_name', as: :autocomplete_role_name
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',         via: 'get'
  match '/signin',  to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :fname, presence: true, length: { minimum: 2}
  validates :lname, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}

  before_save {self.email = email.downcase }


  validates :password, :presence =>true, :confirmation => true, :length => { :within => 6..40 }, :on => :create
  validates :password, :confirmation => true, :length => { :within => 6..40 }, :on => :update, :unless => lambda{ |user| user.password.blank? }

has_secure_password
has_and_belongs_to_many :roles, dependent: :destroy
has_many :books
accepts_nested_attributes_for :roles

def role_name

end

def role_name=(name)
  if name.present?
   r = Role.find_by(name: name)
   unless r.nil?
    self.roles <<  r unless self.roles.include?(r)
  end
end
end

def delete_role(id)
  r = Role.find(id)
  self.roles.delete(r) if self.roles.include?(r)

end

#helps to remember the users who signed up
def User.new_remember_token
  SecureRandom.urlsafe_base64
end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def roles_for_form
    collection = roles.where(role_id: id)
    collection.any? ? collection : roles.build
  end

  #verify if the user is an admin
  def is_admin?
    admin=Role.find_by_id(1)
    if
      self.roles.include?(admin)
      true

    else
      false
    end
  end



  private
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:admin_edit]
  before_filter :authorize, except: [:new, :create]

autocomplete :role, :name, full: true, multiple: true

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #UserMailer.signup_confirmation(@user).deliver
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.html { redirect_to "http://5.135.175.184/users/#{@user.id}", notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
  flag =  params[:user].delete(:password) if params[:user][:password].blank?

  puts " --------------------- #{ params[:user ]}  --- "
    respond_to do |format|
      if @user.update(user_params)
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { redirect_to "http://5.135.175.184/users/#{@user.id}", notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def admin_edit
    @user.roles.build unless @user.roles.size > 0
  end

  def autocomplete_role_name
   term = params[:term]
   if term && !term.empty?
   items = Role.select("distinct name"). where("LOWER(name) like ?", term.downcase + '%'). limit(10).order(:name)
   else
   items = {}
   end
   render :json => json_for_autocomplete(items, :name)
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      #format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.html { redirect_to "http://5.135.175.184/users/", notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :role_name, :password, :password_confirmation, role_ids:[])
    end



end

app/views/users/_form.html.erb
            <%= form_for(@user) do |f| %>
                <div class="form-group">
                    <%= f.text_field :lname, placeholder: "Last name", class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.text_field :fname, placeholder: "First name", class: "form-control"%>
                </div>
                <div class="form-group">
                    <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.password_field :password, placeholder: "password", class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.password_field :password_confirmation, placeholder:"Password confirmation", class: "form-control" %>
                </div>
                <% if request.path == "/signup"%>
                    <div class="form form-group">
                    <%= f.submit "Sign Up", class:"btn btn-primary btn-block"%>
                    </div>
                    <%= link_to 'You already have an account? Login here.', signin_path, class:"btn btn-primary", type:"button", id:"button-signup" %>
                <%elsif request.path == "/users/new"%>
                    <div class="form form-group">
                    <button class="btn btn-primary btn-block" type="submit">Create</button>
                    </div>
                <%else%>
                    <div class="form form-group">
                    <button class="btn btn-primary btn-block" type="submit">Update</button>
                    </div>
                <%end%>
            <%end%>

app/views/users/admin_edit.html.erb
<% if current_user.is_admin? %>
<div class="register-photo">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="form-container">
            <div class="btn-toolbar">
                <div class="btn-group" role="group">
                    <%= link_to 'Show', @user, class:"btn btn-default" %>
                    <%= link_to 'Back', users_path, class:"btn btn-default" %>
                </div>
            </div>
            <h2 class="text-center NewBook"><strong>Admin </strong>Editing User.</h2>
            <%= form_for(@user) do |f| %>
                <div class="form-group">
                    <h4 class="text-center">Fisrt name:</h4>
                    <%= f.text_field :fname, class:"form-control", placeholder:"First name" %>
                </div>
                <div class="form-group">
                    <h4 class="text-center">Last name:</h4>
                    <%= f.text_field :lname, class:"form-control", placeholder:"Last name" %>
                </div>
                <div class="form-group">
                    <h4 class="text-center">Email </h4>
                    <%= f.email_field :email, class:"form-control", placeholder:"Email" %>
                </div>
                <div class="form-group">
                    <h3 class="text-center"><strong>Add roles</strong></h3>
                    <%= f.collection_check_boxes :role_ids, Role.all, :id, :name do |b| %>
                    <div class="checkbox">
                      <%= b.label :class => "control-label"  do%>
                        <%= b.check_box %>
                        <%= b.text%>
                      <% end %>
                    </div>
                    <% end %>
                </div>
                <div class="form form-group">
                    <button class="btn btn-primary btn-block" type="submit">Update</button>
                </div>
            <% end %>
        </div>
    </div>

    <%end%>

app/views/users/edit.html.erb
<div class="register-photo">
    <% if @user.errors.any? %>
                <div id="error_explanation" class="form-container">
                  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                  <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
                <% end %>
        <div class="form-container">
        	<div class="btn-group" role="group">
                <%= link_to 'Show', @user, class:"btn btn-default" %>
                <%= link_to 'Back', users_path, class:"btn btn-default"%>
            </div>
            <h2 class="text-center NewBook"><strong>Editing User</strong></h2>
        	<%= render 'form' %>
        </div>
</div>

app/views/users/index.html.erb
<div class="register-photo">
        <div id="book-frame" class="form-container">
            <div class="btn-toolbar">
                <div class="btn-group" role="group">
                    <% if current_user.is_admin? %>
                      <%= link_to 'New User', new_user_path, class:"btn btn-default" %>
                      <%= link_to 'Roles', roles_path, class:"btn btn-default" %>
                    <% end%>
                </div>
                <div class="btn-group" role="group"></div>
            </div>
            <form>
                <% if current_user.is_admin? %>
                <h3 class="text-center">Listing users</h3>
                <div class="table-responsive" style="padding:36px;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>First name</th>
                                <th>Last name</th>
                                <th>Email </th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        <tbody id="table-library">
                            <% @users.each do |user| %>
                              <tr>
                                <td><%= user.fname %></td>
                                <td><%= user.lname %></td>
                                <td><%= user.email %></td>



                                <td><%= link_to 'Show', user %></td>
                                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>


                              </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <%else%>
                <h3 class="text-center">Connected users</h3>
                <div class="table-responsive" style="padding:36px;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>First name</th>
                                <th>Last name</th>
                                <th>Email </th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        <tbody id="table-library">
                              <tr>
                                <td><%= current_user.fname %></td>
                                <td><%= current_user.lname %></td>
                                <td><%= current_user.email %></td>
                                <td><%= link_to 'Edit', edit_user_path(current_user) %></td>
                              </tr>
                        </tbody>
                    </table>
                </div>
                <%end%>
            </form>
        </div>
    </div>

app/views/users/new.html.erb
<div class="register-photo">
    <% if @user.errors.any? %>
                <div id="error_explanation" class="form-container">
                  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                  <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
                <% end %>
        <div class="form-container">
            <h2 class="text-center NewBook"><strong>Create</strong> an account.</h2>
        	<%= render 'form' %>
        </div>
</div>

app/views/users/show.html.erb
<div class="register-photo">
    <div class="form-container">
        <div class="btn-toolbar">
            <div class="btn-group" role="group">
                <% if current_user.is_admin? %>
                <%= link_to 'Edit', admin_edit_path(@user), class:"btn btn-default" %>
                <% end %>
                <%= link_to 'Back', users_path, class:"btn btn-default" %>
            </div>
        </div>
        <h2 class="text-center NewBook"><strong>Your </strong>profile.</h2>
        <form method="post">
            <div class="form-group">
                <h4 class="text-center">First name: </h4>
                <p class="showP showPUser"><%= @user.fname %></p>
            </div>
            <div class="form-group">
                <h4 class="text-center">Last name: </h4>
                <p class="showP showPUser"><%= @user.lname %></p>
            </div>
            <div class="form-group">
                <h4 class="text-center">Email: </h4>
                <p class="showP showPUser"><%= @user.email %></p>
            </div>
            <% if @user.roles.size > 0 %>
            <div class="form-group">
                <h3 class="text-center"><strong>Current roles</strong></h3>
                <ul class="list-group">
                    <% @user.roles.each do |r| %> 
                    <li class="list-group-item">
                        <span><%=r.name%></span>
                    </li>
                    <%end%>
                </ul>
            </div>
            <%end%>
        </form>
    </div>
</div>