config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get '/admin_edit/:id' => 'users#admin_edit', as: :admin_edit
  resources :books_on_loans
  resources :books do

    get 'check_out', :on => :collection
    get 'check_in', :on => :collection
    get 'list_onloan', :on => :collection
    post 'list_onloan', :on => :collection
    post 'check_out', :on => :collection
    post 'check_in', :on => :collection

    collection do
      get :edit_multiple
      put :update_multiple
    end
  end
   resources :welcome do
     get 'book_search', :on => :collection
     post 'book_search', :on => :collection
   end
  resources :roles_users
  resources :roles
  resources :users do
    collection do
      get 'admin_edit'

      get 'autocomplete_role_name', as: :autocomplete_role_name
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',         via: 'get'
  match '/signin',  to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

  root :to => 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :users
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title , presence: true, length: { minimum: 1}
  validates :Author , presence: true, length: { maximum: 50}
  validates :ISBN , presence: true, length: { maximum: 10}
  validates :Publisher , presence: true, length: { maximum: 50}
  validates :description , presence: true
  validates :Language , presence: true, length: { maximum: 50}
  validates :onloan , presence: true, length: { maximum: 1}

  #search function
  def self.search(search)
    where("title LIKE ? OR Author LIKE ? OR ISBN LIKE ? OR Language LIKE ? OR Publisher LIKE ? ",  "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")

  end



end

app/models/user.rb
class User < ActiveRecord::Base
  validates :fname, presence: true, length: { minimum: 2}
  validates :lname, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}

  before_save {self.email = email.downcase }


  validates :password, :presence =>true, :confirmation => true, :length => { :within => 6..40 }, :on => :create
  validates :password, :confirmation => true, :length => { :within => 6..40 }, :on => :update, :unless => lambda{ |user| user.password.blank? }

has_secure_password
has_and_belongs_to_many :roles, dependent: :destroy
has_many :books
accepts_nested_attributes_for :roles

def role_name

end

def role_name=(name)
  if name.present?
   r = Role.find_by(name: name)
   unless r.nil?
    self.roles <<  r unless self.roles.include?(r)
  end
end
end

def delete_role(id)
  r = Role.find(id)
  self.roles.delete(r) if self.roles.include?(r)

end

#helps to remember the users who signed up
def User.new_remember_token
  SecureRandom.urlsafe_base64
end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def roles_for_form
    collection = roles.where(role_id: id)
    collection.any? ? collection : roles.build
  end

  #verify if the user is an admin
  def is_admin?
    admin=Role.find_by_id(1)
    if
      self.roles.include?(admin)
      true

    else
      false
    end
  end



  private
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  # GET /books
  # GET /books.json


  def index
    @books = Book.all


    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    else
      @books = Book.all.order("created_at DESC")
    end
    @books =@books.page(params[:page]).per_page(5)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new

    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to "http://5.135.175.184/books/#{@book.id}", notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to "http://5.135.175.184/books/#{@book.id}", notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to "http://5.135.175.184/books/", notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_out
    @params = params[:book]
      #param=params[:user]
      title = @params[:title]
      #lname = param[:lname].reject(&:blank?) unless params[:lname].nil?
      @book = Book.find_by_title(title)
      @user = current_user
      if @user == nil
        @note = 'This user is not registered.'
      elsif @book == nil
        @note = 'This book is not in the library.'
      elsif @book.onloan == 1
        @note = 'This book is on loan.'
      else
        @book.onloan = 1
        @book.save
        @books_loaned = BooksOnLoan.create(book_id: @book.id, user_id: @user.id)
        @books_loaned.save
        @note = 'The book has been checked out.'
      end
      respond_to do |format|
        format.html
      end
    end

    def check_in
      @params = params[:book]
      title = @params[:title]
      @book = Book.find_by_title(title)

      if @book != nil
        @book.onloan = 0
        @book.save
        @books_loaned = BooksOnLoan.find_by_book_id(@book.id)
        if @books_loaned != nil
          @books_loaned.destroy
          @note = 'The book has been checked in.'
        else
          @note = 'Error in books_loaned destroy'
        end
      else
        @note = 'Book not found'
      end
      respond_to do |format|
        format.html
      end
    end

    def list_onloan
      @books_loaned = BooksOnLoan.all
      if @books_loaned == nil
        @note = 'No books are on loan.'
      else
        respond_to do |format|
          format.html
        end
      end
    end

    def edit_multiple
      @books = Book.find(params[:book_ids])
    end

    def update_multiple
      @books = Book.update(params[:books].keys,params[:books].values)
      @books.reject! { |p| p.errors.empty? }
      if @books.empty?
        redirect_to "http://5.135.175.184/books/"
      else
        render "edit_multiple"
      end
    end




    private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title,:image, :Author, :ISBN, :Publisher, :Language, :onloan, :description)
    end
  end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :multipart => true } do |f| %>
<div class="form-group">
    <h4>Title </h4>
    <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
</div>
<div class="form-group">
    <h4>Author </h4>
    <%= f.text_field :Author, class:"form-control", placeholder:"Author" %>
</div>
<div class="form-group">
    <h4>Isbn </h4>
    <%= f.number_field :ISBN, class:"form-control", placeholder:"Isbn", min:"0", step:"1" %>
</div>
<div class="form-group">
    <h4>Publisher </h4>
    <%= f.text_field :Publisher, class:"form-control", placeholder:"Publisher" %>
</div>
<div class="form-group">
    <h4>Language </h4>
    <%= f.text_field :Language, class:"form-control", placeholder:"Language" %>
</div>
<div class="form-group">
    <h4>Onloan </h4>
    <%= f.number_field :onloan, class:"form-control", placeholder:"Onloan", min:"0", max:"1", step:"1" %>
</div>
<div class="form-group">
    <h4>Description </h4>
    <%= f.text_area :description, class:"form-control", placeholder:"Description", id:"textarea" %>
</div>
<div class="form-group">
    <h4>Image </h4>
    <%= f.file_field :image %>
</div>
<div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary btn-block" %>
</div>
<% end %>

app/views/books/check_in.html.erb
<div class="register-photo">
	<div class="form-container">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Back', books_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>Check </strong>in.</h2>
		<form method="post">
			<div class="form-group">
				<h3 class="text-center"> <%= @note %> </h3>
			</div>
		</form>
	</div>
</div>

app/views/books/check_out.html.erb
<div class="register-photo">
	<div class="form-container">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Back', books_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>Check </strong>out.</h2>
		<form method="post">
			<div class="form-group">
				<h3 class="text-center"> <%= @note %> </h3>
			</div>
		</form>
	</div>
</div>

app/views/books/edit.html.erb
<% if current_user.is_admin? %>
<div class="register-photo">
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-container">
   <div class="btn-toolbar">
    <div class="btn-group" role="group">
      <%= link_to 'Show', @book, class:"btn btn-default" %>
      <%= link_to 'Back', books_path, class:"btn btn-default"%>
    </div>
  </div>
  <h2 class="text-center" id="NewBook"><strong>Edit Book</strong></h2>
  <%= render 'form' %>
  </div>
</div>
<%end%>

app/views/books/edit_multiple.html.erb
<% if current_user.is_admin? %>
<div class="register-photo">
  <div class="form-container">
    <h1 style="text-align: center;">Edit Checked Books</h1>

    <%= form_tag update_multiple_books_path, method: :put do %>
    <% @books.each do |book| %>
    <h2>Livre: <%= book.title %></h2>
    <%= fields_for "books[]", book do |f|%>
    <% if book.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
            <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-group">
        <h4>Title </h4>
        <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
    </div>
    <div class="form-group">
        <h4>Author </h4>
        <%= f.text_field :Author, class:"form-control", placeholder:"Author" %>
    </div>
    <div class="form-group">
        <h4>Isbn </h4>
        <%= f.number_field :ISBN, class:"form-control", placeholder:"Isbn", min:"0", step:"1" %>
    </div>
    <div class="form-group">
        <h4>Publisher </h4>
        <%= f.text_field :Publisher, class:"form-control", placeholder:"Publisher" %>
    </div>
    <div class="form-group">
        <h4>Language </h4>
        <%= f.text_field :Language, class:"form-control", placeholder:"Language" %>
    </div>
    <div class="form-group">
        <h4>Onloan </h4>
        <%= f.number_field :onloan, class:"form-control", placeholder:"Onloan", min:"0", max:"1", step:"1" %>
    </div>
    <div class="form-group">
        <h4>Description </h4>
        <%= f.text_area :description, class:"form-control", placeholder:"Description", id:"textarea" %>
    </div>
    <div class="form-group">
        <h4>Image </h4>
        <%= f.file_field :image %>
    </div>
    <br>
    <br>
    <br>
    <% if book != @books.last %>
    <div class="form-group">
        <div id="line"></div>
    </div>
    <% end %>             
    <% end %>
    <% end %>
    <%= submit_tag "Update", :class => "btn btn-primary btn-block" %>
</div>
<% end %>
</div>
<%end%>

app/views/books/index.html.erb
<div class="register-photo">
  <div id="book-frame" class="form-container">
    <div class="btn-toolbar">
      <div class="btn-group" role="group">
        <%if current_user.is_admin?%>
            <%= link_to 'New Book', new_book_path, class:"btn btn-default", type:"button" %>
            <%= link_to 'List books on loan', list_onloan_books_path, class:"btn btn-default" %>
        <%end%>
      </div>
    </div>
    <%= form_tag(books_path, :method => "get",) do %>
    <h3 class="text-center">Search book.</h3>
    <br/>

    <br/>
    <%= text_field_tag :search, params[:search], placeholder: "Search Book", class:"form-control" %>

    <%= submit_tag "Search", class:"btn btn-default btn-block button"%>

    <% end %>
    <% if @books.blank? %>
    <h4 style="margin: 0px 3%">No books found</h4>
    <% end %>
    <%= form_tag edit_multiple_books_path, method: :get do %>

    <h3 class="text-center">Listing Books.</h3>

    <div class="table-responsive" style="padding:36px;">
      <table class="table">
        <thead>
          <tr>
            <% if current_user.is_admin? %>
            <th></th>
            <%end%>
            <th>Title</th>
            <th>Author</th>
            <th>Isbn</th>
            <th>Publisher</th>
            <th>Language</th>
            <th>Onloan</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody id="table-library">
          <% @books.each do |book| %>
          <tr>
            <% if current_user.is_admin? %>
            <td><%= check_box_tag "book_ids[]", book.id %></td>
            <%end%>
            <td><%= book.title %></td>
            <td><%= book.Author %></td>
            <td><%= book.ISBN %></td>
            <td><%= book.Publisher %></td>
            <td><%= book.Language %></td>
            <td><%= book.onloan %></td>

            <td><%= link_to 'Show', book %></td>
            <% if current_user.is_admin? %>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% if current_user.is_admin? %>
      <%= submit_tag "Edit Checked", :class => "btn btn-default btn-block button" %>
      <% end %>
      <% end %>
    </div>
    <%= will_paginate @books, previous_label: h("<"), next_label: h(">") %>

    <%= form_for :book, url: {action: :check_out} do |form| %>               
    <h3 class="text-center">Check out.</h3>
    <br/>
    <span style="text-align:center;display:block;font-size:16px;">Title: </span>
    <%= form.text_field :title, class:"form-control book-search", placeholder:"Title"%>
    <%= form.submit "Check Out", class:"btn btn-default btn-block button" %>
    <% end %>
    <%= form_for :book, url: {action: :check_in} do |form| %>
    <h3 class="text-center">Check in.</h3>
    <br/>
    <span style="text-align:center;display:block;font-size:16px;">Title: </span>
    <%= form.text_field :title, class:"form-control book-search", placeholder:"Title"%>
    <%= form.submit "Check In", class:"btn btn-default btn-block button" %>
    <% end %>
  </div>
</div>    

app/views/books/list_onloan.html.erb
<div class="register-photo">
	<div class="form-container form-container-table">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Back', books_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>List</strong> Books On Loan.</h2>
		<form method="post">
			<div class="form-group">
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th>Author </th>
								<th>Title </th>
								<th>ISBN </th>
								<th>First name</th>
								<th>Last name</th>
								<th>Email </th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% for i in @books_loaned %>
							<tr>
								<td><%= i.book.try(:Author) %></td>
								<td><%= i.book.try(:title) %></td>
								<td><%= i.book.try(:ISBN )%></td>
								<td><%= i.user.try(:fname) %></td>
								<td><%= i.user.try(:lname) %></td>
								<td><%= i.user.try(:email) %></td>
								
							</tr>
							<%end%>
						</tbody>
					</table>
					
				</div>
			</div>
		</form>
	</div>
</div>

app/views/books/new.html.erb
<% if current_user.is_admin? %>
<div class="register-photo">
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-container">
   <div class="btn-toolbar">
    <div class="btn-group" role="group">
      <%= link_to 'Show', @book, class:"btn btn-default" %>
      <%= link_to 'Back', books_path, class:"btn btn-default"%>
    </div>
  </div>
  <h2 class="text-center" id="NewBook"><strong>New Book</strong></h2>
  <%= render 'form' %>
</div>
</div>
<%end%>

app/views/books/show.html.erb
<div class="register-photo">
    <div class="form-container">
        <div class="btn-toolbar">
            <div class="btn-group" role="group">
                <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_book_path(@book), class:"btn btn-default" %>
                <% end %>
                <%= link_to 'Back', books_path, class:"btn btn-default" %>
            </div>
        </div>
        <h2 class="text-center NewBook"><strong>Book</strong></h2>
        <form method="post">
            <div class="form-group">
                <h4>Title: </h4>
                <p class="showP"><%= @book.title %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Author: </h4>
                <p class="showP"><%= @book.Author %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Isbn: </h4>
                <p class="showP"><%= @book.ISBN %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Publisher: </h4>
                <p class="showP"><%= @book.Publisher %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Language: </h4>
                <p class="showP"><%= @book.Language %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Onloan: </h4>
                <p class="showP"><%= @book.onloan %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Description: </h4>
                <p class="showP"><%= @book.description %></p>
                <br>
            </div>
            <div class="form-group">
                <h4>Image: </h4>
                <%= image_tag @book.image.url(:med) %>
            </div>
        </form>
    </div>
</div>