config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get '/admin_edit/:id' => 'users#admin_edit', as: :admin_edit
  resources :books_on_loans
  resources :books do

    get 'check_out', :on => :collection
    get 'check_in', :on => :collection
    get 'list_onloan', :on => :collection
    post 'list_onloan', :on => :collection
    post 'check_out', :on => :collection
    post 'check_in', :on => :collection

    collection do
      get :edit_multiple
      put :update_multiple
    end
  end
   resources :welcome do
     get 'book_search', :on => :collection
     post 'book_search', :on => :collection
   end
  resources :roles_users
  resources :roles
  resources :users do
    collection do
      get 'admin_edit'

      get 'autocomplete_role_name', as: :autocomplete_role_name
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',         via: 'get'
  match '/signin',  to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

  root :to => 'welcome#index'

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users, dependent: :destroy

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :adminonly
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to "http://5.135.175.184/roles/#{@role.id}", notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to "http://5.135.175.184/roles/#{@role.id}", notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to "http://5.135.175.184/roles/", notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description, :level)
    end
end

app/views/roles/_form.html.erb
<% if current_user.is_admin? %>
<%= form_for(@role) do |f| %>
<div class="form-group">
  <h4>Name </h4>
  <%= f.text_field :name, class:"form-control", placeholder:"Name" %>
</div>
<div class="form-group">
  <h4>Description </h4>
  <%= f.text_area :description, class:"form-control", placeholder:"Description", id:"textarea" %>
</div>
<div class="form-group">
  <h4>Level </h4>
  <%= f.number_field :level, class:"form-control", placeholder:"level", min:"0", step:"1" %>
</div>
<div class="form-group">
  <%if request.path == "/roles/new"%>
  <button class="btn btn-primary btn-block" type="submit">Create</button>
  <%else%>
  <div class="form form-group">
    <button class="btn btn-primary btn-block" type="submit">Update</button>
  </div>
  <%end%>
</div>
<%end%>
<%end%>

app/views/roles/edit.html.erb
<% if current_user.is_admin? %>
<div class="register-photo">
	<% if @role.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

		<ul>
			<% @role.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-container">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Show', @role, class:"btn btn-default" %>
				<%= link_to 'Back', roles_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>Edit</strong> Role.</h2>
		<%= render 'form' %>
	</div>
</div>
<% end %>

app/views/roles/index.html.erb
<div class="register-photo">
  <div class="form-container">
    <div class="btn-toolbar">
      <div class="btn-group" role="group">
        <%= link_to 'New Role', new_role_path, class:"btn btn-default" %>
        <%= link_to 'Back', users_path, class:"btn btn-default" %>
      </div>
    </div>
    <h2 class="text-center NewBook"><strong>Listing </strong>roles.</h2>
    <form method="post">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Level</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @roles.each do |role| %>
            <tr>
              <td><%= role.name %></td>
              <td><%= role.description %></td>
              <td><%= role.level %></td>
              <td><%= link_to 'Show', role %></td>
              <td><%= link_to 'Edit', edit_role_path(role) %></td>
              <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </form>
  </div>
</div>

app/views/roles/new.html.erb
<div class="register-photo">
	<% if @role.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

		<ul>
			<% @role.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-container">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Back', roles_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>Edit</strong> role.</h2>
		<%= render 'form' %>
	</div>
</div>

app/views/roles/show.html.erb
<div class="register-photo">
	<div class="form-container">
		<div class="btn-toolbar">
			<div class="btn-group" role="group">
				<%= link_to 'Edit', edit_role_path(@role), class:"btn btn-default" %> 
				<%= link_to 'Back', roles_path, class:"btn btn-default" %>
			</div>
		</div>
		<h2 class="text-center NewBook"><strong>Roles</strong>.</h2>
		<form method="post">
			<div class="form-group">
				<h4 class="text-center">Name: </h4>
				<p class="showP showPUser"><%= @role.name %></p>
			</div>
			<div class="form-group">
				<h4 class="text-center">Description:</h4>
				<p class="showP showPUser"><%= @role.description %></p>
			</div>
			<div class="form-group">
				<h4 class="text-center">Level: </h4>
				<p class="showP showPUser"><%= @role.level %></p>
			</div>
		</form>
	</div>
</div>