config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get '/admin_edit/:id' => 'users#admin_edit', as: :admin_edit
  resources :books_on_loans
  resources :books do

    get 'check_out', :on => :collection
    get 'check_in', :on => :collection
    get 'list_onloan', :on => :collection
    post 'list_onloan', :on => :collection
    post 'check_out', :on => :collection
    post 'check_in', :on => :collection

    collection do
      get :edit_multiple
      put :update_multiple
    end
  end
   resources :welcome do
     get 'book_search', :on => :collection
     post 'book_search', :on => :collection
   end
  resources :roles_users
  resources :roles
  resources :users do
    collection do
      get 'admin_edit'

      get 'autocomplete_role_name', as: :autocomplete_role_name
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',         via: 'get'
  match '/signin',  to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'

  root :to => 'welcome#index'

end

app/views/layouts/_footer.html.erb
<div class="footer-dark">
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-md-offset-0 col-sm-4 col-sm-offset-4 item social"> 
              <a href="#"><i class="icon ion-social-facebook"></i></a>
              <a href="#"><i class="icon ion-social-twitter"></i></a>
              <a href="#"><i class="icon ion-social-snapchat"></i></a>
              <a href="#"><i class="icon ion-social-instagram"></i></a>
            </div>
          </div>
          <p class="copyright">Virtual Library © 2016</p>
        </div>
      </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>

  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <%= stylesheet_link_tag "Navigation-with-Button1" %>
  <%= stylesheet_link_tag "Navigation-with-Search1" %>
  <%= stylesheet_link_tag "Footer-Clean" %>
  <%= stylesheet_link_tag "Footer-Dark" %>
  <%= stylesheet_link_tag "Footer-Dark-1" %>
  <%= stylesheet_link_tag "Login-Form-Clean" %>
  <%= stylesheet_link_tag "Login-Form-Clean-1" %>
  <%= stylesheet_link_tag "Login-Form-Dark" %>
  <%= stylesheet_link_tag "Registration-Form-with-Photo" %>
  <%= stylesheet_link_tag "styles" %>
  <%= csrf_meta_tags %>

  <nav class="navbar navbar-default navigation-clean-button">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Virtual Library", root_path, color: "rgb(55, 67, 77)", class:"navbar-brand navbar-link" %>
          <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav">
            <% if signed_in? %>
            <li role="presentation">
              <%= link_to "Home", root_path, color: "rgb(55, 67, 77)" %>
            </li>
            <li role="presentation">
              <%= link_to "Book", books_path, color: "rgb(55, 67, 77)" %>
            </li>
            <li role="presentation" class="size">
              <%= link_to "Users", users_path, color: "rgb(55, 67, 77)" %>
            </li>
            <li role="presentation" class="signup">
              <%= link_to "Sign out", signout_path, method: "delete", style:"background:#56c6c6;border-radius:20px;color:#fff;box-shadow:none;border:none;text-shadow:none;padding:10px 22px;transition:background-color 0.25s;float:right;"  %>
            </li>
            <% else %>
            <li role="presentation" class="size">
              <%= link_to "Home", root_path, color: "rgb(55, 67, 77)" %>
            </li>
            <li role="presentation">
              <%= link_to "Sign in", signin_path, style:"margin-bottom:0;padding:9px 18px;color:rgb(119,119,119);"  %>
            </li>
            <li role="presentation">
              <%= link_to "Sign up", signup_path, style:"background:#56c6c6;border-radius:20px;color:#fff;box-shadow:none;border:none;text-shadow:none;padding:10px 22px;transition:background-color 0.25s;float:right;" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
  </nav>
</head>

<body>
  <p id="notice"><%= notice %></p>



<%= yield %>
<%= render "layouts/footer" %>



</body>
</html>